### ISSUE TITLE
Add carousel for partner companies

### ISSUE THREAD

**Issue by ocodista** [ocodista/trampar-de-casa#102]
The list is growing so we need a more dynamic way to display companies that support the project.

I think a carousel would be nice!

**Comment by matheus-foscarinid** [comment]
Hi there! I really like this project and I'd love to contribute for this issue.

Do you have an example of a carousel that you think would suit the project? and should it be here? 
![image](https://github.com/ocodista/trampar-de-casa/assets/57161520/9ca1d123-3526-42a6-ae8f-8440fa608d4f)

**Comment by ocodista** [comment]
Hello @matheus-foscarinid, thanks for commenting.

I don't already have a carousel style for this project, so you're free to choose one that fits with our current UI.

**Comment by albertofp** [comment]
Working on this aswell.
Trying to keep it from jumping at the end of the animation, as seen below

![marquee](https://github.com/ocodista/trampar-de-casa/assets/52082366/0bf06ffd-f108-4009-94fa-f065f413bebe)

**Comment by ocodista** [comment]
That's a great start @albertofp, thank you!!
