### ISSUE TITLE
Implement resend e-mail button if trying to login when not verified

### ISSUE THREAD

**Issue by pedrobruneli** [ocodista/trampar-de-casa#131]
- If user tries to register an email and that email is already registered but not verified, show an option to resend the email validation

**Comment by ocodista** [comment]
Thank you @pedrobruneli for suggesting this improvement.

We would love to see a PR implementing it, would you be able to work on it?

**Comment by pedrobruneli** [comment]
Sure! @ocodista

**Comment by sudoevans** [comment]
Hello, Please assign me this issue.
From Tublian.
Thank you.

**Comment by ocodista** [comment]
@sudoevans feel free to open a PR for it.

As we don't have any PR open to solve this issue, the first one to solve the problem wins.
