### ISSUE TITLE
Improve readme

### ISSUE THREAD

**Issue by gutogalego** [ocodista/trampar-de-casa#137]
![Screenshot 2023-10-11 at 11 00 18 AM](https://github.com/ocodista/trampar-de-casa/assets/31139680/e929ec18-81d6-4fa2-bb63-8639fde71058)

This is a little misleading. To run `npm run db-start` we need to be in packages/db folder. I think we can make it a bit more clear.

Another thing that is not super clear is where to create the .env. Maybe we can specify that it should be inside /web. 

Lastly, maybe some documentation about EMAIL_KEY and EMAIL_PASS? But that can be another issue.

**Comment by ocodista** [comment]
Hi Guto, you're right, it's probably outdated.

Would you be able to open a PR?
