### ISSUE TITLE
Add global loader

### ISSUE THREAD

**Issue by ocodista** [ocodista/trampar-de-casa#14]
## Technologies
- React
- TailwindCSS

## Goal
- The goal is to implement a global loader to be used on fetch requests
- The loader should fit the screen size and act as an overlay. It should have opacity between (.5 - .8)
- Maybe use React Context to create a GlobalContext on the app/layout.tsx file
- It must be pretty

**Comment by raphaelvdossantos** [comment]
The PR #20 closes this issue.

**Comment by ocodista** [comment]
Thank you!
