### ISSUE TITLE
Design a companies page

### ISSUE THREAD

**Issue by ocodista** [ocodista/trampar-de-casa#163]
Currently, all companies that support the project are displayed on the landing page inside a carousel, but the list is growing (not that bad of a problem to have), so we need a new page.

I'm not a great UX/UI designer, if no design is proposed, I'll probably use standard tailwind + shadcn/ui but if you think you can design a great, modern companies page, with great copy, ux/ui in a figma, you're welcome to share with us.

**Comment by Pooja1672** [comment]
HI @ocodista , I would like to work on this issue .Can you assign it to me?

**Comment by suamirochadev** [comment]
Olá eu gostaria de poder fazer isso! Vou começar imediatamente e envio aqui :)

**Comment by suamirochadev** [comment]
Fiz esse prototipo pra visualizarem como está a UI, aceito sugestões, criticas construtivas rs e estou aqui para ajudar.

https://www.figma.com/proto/TblKdDj6FI6oeFFslDtEnx/Trampar-de-Casa?page-id=0%3A1&type=design&node-id=1-3&viewport=638%2C431%2C0.12&t=q0IBfdaMdpj3tu3w-1&scaling=min-zoom&starting-point-node-id=1%3A3&mode=design

Qualquer pessoa com o link pode ver o prototipo e interagir.

**Comment by suamirochadev** [comment]
> > Fiz esse prototipo pra visualizarem como está a UI, aceito sugestões, criticas construtivas rs e estou aqui para ajudar.
> > 
> > https://www.figma.com/proto/TblKdDj6FI6oeFFslDtEnx/Trampar-de-Casa?page-id=0%3A1&type=design&node-id=1-3&viewport=638%2C431%2C0.12&t=q0IBfdaMdpj3tu3w-1&scaling=min-zoom&starting-point-node-id=1%3A3&mode=design
> > 
> > Qualquer pessoa com o link pode ver o prototipo e interagir.
> 
> 
> pra mim não está acessando, só fica tudo preto 🙃
> ![Image](https://github.com/ocodista/trampar-de-casa/assets/38724911/6e7624cb-8e4c-4bbe-8476-6b57031cd4ae)
> 
> 

Oii! O link do projeto atualizado foi passado somente para o caio para aprovação.

Assim que for aprovado creio que ele mesmo vá notificar por aqui, ok?

**Comment by nathan-guedes** [comment]
> > > Fiz esse prototipo pra visualizarem como está a UI, aceito sugestões, criticas construtivas rs e estou aqui para ajudar.
> > > https://www.figma.com/proto/TblKdDj6FI6oeFFslDtEnx/Trampar-de-Casa?page-id=0%3A1&type=design&node-id=1-3&viewport=638%2C431%2C0.12&t=q0IBfdaMdpj3tu3w-1&scaling=min-zoom&starting-point-node-id=1%3A3&mode=design
> > > Qualquer pessoa com o link pode ver o prototipo e interagir.
> > 
> > 
> > pra mim não está acessando, só fica tudo preto 🙃
> > ![Image](https://private-user-images.githubusercontent.com/38724911/301282091-6e7624cb-8e4c-4bbe-8476-6b57031cd4ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MzIzOTAsIm5iZiI6MTcwNjczMjA5MCwicGF0aCI6Ii8zODcyNDkxMS8zMDEyODIwOTEtNmU3NjI0Y2ItOGU0Yy00YmJlLTg0NzYtNmI1NzAzMWNkNGFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDIwMTQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzZGY3MjE3NjQwZjIzZDI4MjBjMGI0NTFlMWI2ZGE5MWZiZTFjM2E0OTI0N2E2NTA2MjFmMzA3N2VlZWEyNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jOcbEqIMD8V423A1-N0Bjf4sx3E5hZSzQufK8C78dUM)
> 
> Oii! O link do projeto atualizado foi passado somente para o caio para aprovação.
> 
> Assim que for aprovado creio que ele mesmo vá notificar por aqui, ok?

ah entendi, fico feliz que não fui eu que tava fazendo merda auhdsuhduasd, tem algo que eu possa ajudar?

**Comment by suamirochadev** [comment]
> > > > Fiz esse prototipo pra visualizarem como está a UI, aceito sugestões, criticas construtivas rs e estou aqui para ajudar.
> > > > https://www.figma.com/proto/TblKdDj6FI6oeFFslDtEnx/Trampar-de-Casa?page-id=0%3A1&type=design&node-id=1-3&viewport=638%2C431%2C0.12&t=q0IBfdaMdpj3tu3w-1&scaling=min-zoom&starting-point-node-id=1%3A3&mode=design
> > > > Qualquer pessoa com o link pode ver o prototipo e interagir.
> > > 
> > > 
> > > pra mim não está acessando, só fica tudo preto 🙃
> > > ![Image](https://private-user-images.githubusercontent.com/38724911/301282091-6e7624cb-8e4c-4bbe-8476-6b57031cd4ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MzIzOTAsIm5iZiI6MTcwNjczMjA5MCwicGF0aCI6Ii8zODcyNDkxMS8zMDEyODIwOTEtNmU3NjI0Y2ItOGU0Yy00YmJlLTg0NzYtNmI1NzAzMWNkNGFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDIwMTQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzZGY3MjE3NjQwZjIzZDI4MjBjMGI0NTFlMWI2ZGE5MWZiZTFjM2E0OTI0N2E2NTA2MjFmMzA3N2VlZWEyNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jOcbEqIMD8V423A1-N0Bjf4sx3E5hZSzQufK8C78dUM)
> > 
> > 
> > Oii! O link do projeto atualizado foi passado somente para o caio para aprovação.
> > Assim que for aprovado creio que ele mesmo vá notificar por aqui, ok?
> 
> ah entendi, fico feliz que não fui eu que tava fazendo merda auhdsuhduasd, tem algo que eu possa ajudar?


Pode siimm

o link do figma é esse aqui: https://www.figma.com/file/TblKdDj6FI6oeFFslDtEnx/Trampar-de-Casa?type=design&node-id=43%3A1329&mode=design&t=gxQctmjg9fi2y7TP-1
