### ISSUE TITLE
Validation bug in LinkedIn field (page: https://www.trampardecasa.com.br/subscribers/profile/{id})

### ISSUE THREAD

**Issue by ViniciusPradoV** [ocodista/trampar-de-casa#185]
Hello, hope you guys are doing well!

I've stumbled into this bug while trying to customize my subscription to Trampar de Casa:

Validation on field for LinkedIn profile link:

![image](https://github.com/ocodista/trampar-de-casa/assets/31973401/7f4773ff-b9bb-4df3-9fc8-39e992258431)

Thanks for your work on this project, by the way!

**Comment by rharison** [comment]
HI @ocodista, I would like to act on this issue. How to procedure?

**Comment by ocodista** [comment]
Hello @rharison, thank you!

First thing is to:
- Fork the project
- Read the README.md file and setup your local environment
- Replicate the issue and work on a fix


Once you have a fix, open a PR.
