### ISSUE TITLE
[ptbr] Ei contribuidor, quer adesivo? 

### ISSUE THREAD

**Issue by ocodista** [ocodista/trampar-de-casa#187]
Os 10 primeiros contribuidores que postarem aqui link da contribuição + me chamarem no Twitter/LinkedIn vão ganhar adesivos.

Funcionará assim:
- Posta aqui com o link do PR mergeado + print da mensagem que me mandou no Twitter/LinkedIn.
- Responderei confirmando que ganhou e pedindo endereço.
- Aguarde os adesivos chegarem (pode demorar, mas vai chegar, na faixa!)

Valendo!

**Comment by rharison** [comment]
**Link PR:** https://github.com/ocodista/trampar-de-casa/pull/186lin
<img width="633" alt="image" src="https://github.com/ocodista/trampar-de-casa/assets/100204821/07abb3a1-3cbc-4041-a74e-8463e8a5ca62">

**Comment by albertofp** [comment]
Quais adesivos 🤔

**Comment by jozemaria** [comment]
> Quais adesivos 🤔

Esses:
<img width="283" alt="image" src="https://github.com/ocodista/trampar-de-casa/assets/29362845/a162b354-ccba-46b1-9b6b-261d1abea5e6">

**Comment by ericoschuch** [comment]
Da hora

**Comment by andretibr** [comment]
Esperando o Adesivo o link da compra....

**Comment by kevinCubas** [comment]
Boaa, aqui um dos meus PRs:
https://github.com/ocodista/trampar-de-casa/pull/162

Mensagem para o brabo 🔥
![image](https://github.com/ocodista/trampar-de-casa/assets/61201131/23240cc5-6a2f-4859-8064-614f34db4d80)

**Comment by pedrobruneli** [comment]
@ocodista ainda tem adesivos??? minha PR #133

**Comment by andretibr** [comment]
Espero um dia receber


Em ter., 14 de nov. de 2023 às 16:41, Kevin Cubas ***@***.***>
escreveu:
