### ISSUE TITLE
Migrar `email-sender` para Go.

### ISSUE THREAD

**Issue by daniloraisi** [ocodista/trampar-de-casa#198]
# Realizar a migração do app `email-sender` para Go.

## Qual o objetivo?
Realizar a migração do serviço de envio de e-mails para Go e atualizar a documentação.

## Apps envolvidos
- `auto-email-sender/email-sender`
- Shared code

**Comment by albertofp** [comment]
Qual seria o motivo para migrar? Vale explorar essa ideia? @ocodista
