### ISSUE TITLE
O que falta para a feature "Página para Empresas Parceiras"?

### ISSUE THREAD

**Issue by scarletquasar** [ocodista/trampar-de-casa#212]
É necessária ajuda? Existem detalhes pra montar essa parte? Gostaria de contribuir

**Comment by ocodista** [comment]
Atualmente temos esse [Figma](https://www.figma.com/file/hUDsH8TwKdRax3XNGtkzZh/Trampar-de-Casa?type=design&node-id=0-1&mode=design&t=8ohPXcO0jdQbassW-0), criado pela [@marihemoth](https://twitter.com/marihemoth) com um layout inicial para a página de empresas que apoiam.

O objetivo principal é listar empresas que:

- Apoiaram/apoiam o projeto (talvez com um badge ou cor diferente)
- Que possuem vagas 100% remotas
- Que trabalham no modelo 100% remoto (híbrido não, presencial não)


O @anti-duhring havia comentado que começaria a trabalhar nessa feature na semana passada, mas se ele não responder aqui e você quiser começar, fique à vontade, toda ajuda é bem-vinda 😁

**Comment by scarletquasar** [comment]
Certo, vou esperar ele aparecer. Mas já vou ficar de olho no repo pra ver como eu conseguiria fazer as contribuições, entender o contexto e tal

**Comment by MarlonX19** [comment]
Pessoal, como está o andamento dessa issue? Aparentemente não está sendo trabalho nela, certo? Gostaria de ajudar

**Comment by ocodista** [comment]
Então, por enquanto está parada (infelizmente), estou sem tempo ultimamente e trabalhando na seção de depoimentos (de quem já trabalha remoto).

@MarlonX19 ou @scarletquasar, sintam-se a vontade para trabalhar nela se conseguirem, valeu!
