### ISSUE TITLE
Add a Twitter @mention section to the landing page

### ISSUE THREAD

**Issue by ocodista** [ocodista/trampar-de-casa#223]

**Comment by sergiohdljr** [comment]
i would like to help, can you be more specific ?

**Comment by ocodista** [comment]
Yes @sergiohdljr, thank you!

I would like to have a carrousel section with embedded tweets about people talking about Trampar de Casa.

It can be static (maybe a json list with: username, name, body, createdAt)

The main thing is creating the layout of the tweets in a way that it fits on the landing page
