### ISSUE TITLE
Fix contributors section on Readme

### ISSUE THREAD

**Issue by ocodista** [ocodista/trampar-de-casa#27]
The contributors section is broken.

I used the website contributors.rock but it simply never gets updated.

We want to display all contributors avatars on the readme file but it needs to be automatically updated.

**Comment by elidakirigo** [comment]
hello, I'd like to help assist in the display of all contributors to this repository. assign, please. thanks

**Comment by ocodista** [comment]
You got it, feel free to open a PR whenever you're ready.

Thank you!

**Comment by ocodista** [comment]
Closing this one because of https://github.com/ocodista/trampar-de-casa/pull/43

**Comment by elidakirigo** [comment]
okay @ocodista
