### ISSUE TITLE
Create new logo

### ISSUE THREAD

**Issue by ocodista** [ocodista/trampar-de-casa#32]
The current one is not good and it was created in 5 minutes using midjourney.

We could use a new one.

**Comment by tgmarinho** [comment]
![Screenshot 2023-06-26 at 23 07 30](https://github.com/ocodista/trampar-de-casa/assets/380327/fb9ba6e5-0ca2-49a3-a6ba-cbf61be9ac27)
![Screenshot 2023-06-26 at 23 07 38](https://github.com/ocodista/trampar-de-casa/assets/380327/d7b5db4e-ea72-44c7-992b-bf24c61d7881)

some ideas inspired by @renata_rko

**Comment by tgmarinho** [comment]
![Screenshot 2023-06-26 at 23 10 03](https://github.com/ocodista/trampar-de-casa/assets/380327/f84b327a-c2fd-42db-b1db-f877ce5f7448)

**Comment by tgmarinho** [comment]
![Screenshot 2023-06-26 at 23 15 44](https://github.com/ocodista/trampar-de-casa/assets/380327/c1326738-c2a2-4042-8c13-3d032998b8cc)

**Comment by renatarko** [comment]
Hii, I created some ideias to the new Logo!

![TRAMPAR DE CASA TRAMR DE CASA](https://github.com/ocodista/trampar-de-casa/assets/106983293/02a8abc2-c176-4b0e-9d5f-4a02367cdea1)

**Comment by ocodista** [comment]
@tgmarinho @renatarko Thank you both for all the options given.

After careful consideration with @anti-duhring, we both decided to choose this one 
![image](https://github.com/ocodista/trampar-de-casa/assets/19851187/707be0b4-7acf-426d-8190-4e17ae121790)


@renatarko could you please prepare the assets for this icon and upload or send to us via .zip folder?

Thank you!!!

**Comment by renatarko** [comment]
Oh yes, of course.. @ocodista  I'll send !! 😊

**Comment by renatarko** [comment]
I created a PR and made the uploading..
Link of PR ⤵️

https://github.com/ocodista/trampar-de-casa/pull/52

**Comment by anti-duhring** [comment]
Closed because of #52
