### ISSUE TITLE
Improve SEO of HomePage

### ISSUE THREAD

**Issue by ocodista** [ocodista/trampar-de-casa#40]
NextJS has the metadata object that helps users finding the page over the web.

There are probably other things to fix related to SEO.

It would help us a lot!

**Comment by anti-duhring** [comment]
PR #50 was mentioned by @raphaelvdossantos but I don't think it solved the SEO problem. We need this kind of metada config: https://nextjs.org/docs/app/building-your-application/optimizing/metadata

**Comment by raphaelvdossantos** [comment]
> PR #50 was mentioned by @raphaelvdossantos but I don't think it solved the SEO problem. We need this kind of metada config: https://nextjs.org/docs/app/building-your-application/optimizing/metadata

Agree, my PR was just an improvement on more basic stuff. There is a lot of room for improvement

**Comment by anti-duhring** [comment]
> > PR #50 was mentioned by @raphaelvdossantos but I don't think it solved the SEO problem. We need this kind of metada config: https://nextjs.org/docs/app/building-your-application/optimizing/metadata
> 
> Agree, my PR was just an improvement on more basic stuff. There is a lot of room for improvement

No problem, thanks for you help! We are just gonna keep this issue open until this metadata config is solved
