### ISSUE TITLE
Create a new branch <develop>

### ISSUE THREAD

**Issue by gabrielSouzaDevWeb** [ocodista/trampar-de-casa#65]
This branch will serve to simulate the development environment and will also be the branch that will receive the pull request merges

**Comment by ocodista** [comment]
@anti-duhring let's talk about this one.

Currently the app is really small, we have CI/CD in place and we plan to use trunk-based development with feature flags.

In my opinion a develop branch may be good in the future, not right now.

**Comment by tgmarinho** [comment]
main and pr-preview branches are good enough for now

**Comment by ocodista** [comment]
Closing for now, I think we're good without a develop branch for now.
