### ISSUE TITLE
Fix global prettier/eslint config

### ISSUE THREAD

**Issue by ocodista** [ocodista/trampar-de-casa#66]
It is currently broken.

Files are not formatted.

After watching https://www.youtube.com/watch?v=Cd-gBxzcsdA I now understand that:
- eslint should lint
- prettier should format

We can use the default configs for prettier.

The only thing is that it needs to be consistent across all packages and apps.

**Comment by gabrielSouzaDevWeb** [comment]
I'm work it

**Comment by gabrielSouzaDevWeb** [comment]
https://github.com/ocodista/trampar-de-casa/pull/68
