### ISSUE TITLE
"db-seed" exits with TypeError

### ISSUE THREAD

**Issue by albertofp** [ocodista/trampar-de-casa#69]
Steps to reproduce: section "Como subir o banco de dados localmente" up until step 7

Command exists with error: 

Running seed command `npx ts-node prisma/seed.ts` ...
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for .../trampar-de-casa/apps/web/prisma/seed.ts

Anyone else getting this while trying to set up the local environment?

**Comment by hereisjohnny2** [comment]
I tried to run locally and faced a few issues, but nothing like this error. Are you running this on which directory? 

The README says to run in apps/web but that did not worked, so I tried at the packages/db, with a proper .env file and I had some progress. I also needed to run npx prisma db push before seed the db.

**Comment by albertofp** [comment]
The issue I described was when I tried to run `npm run db-start` then `npm run db-seed` inside `apps/web`

Tried the same again and it seems the script was removed from that package.json.  Will try following what you mentioned.

Either way, I feel like that portion of the README needs improvement as it is pretty unclear and/or outdated

**Comment by ocodista** [comment]
@albertofp 
You're right, we're waiting on the issue #85 to update the README and close this one too.

Would you have time to see if you can tackle it?

**Comment by albertofp** [comment]
Don't have any experience with Docker yet, but I'll see if I can get it done this week and update the docs when it's merged
